#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# --- Simple screenshot script using maim and AwesomeWM API
# --
# -- Accepts `area` and `full` string args
# --
# -- For more details check `man maim`
# --
# -- @author manilarome &lt;gerome.matilla07@gmail.com&gt;
# -- @copyright 2020 manilarome
# -- @script snap
# ----------------------------------------------------------------------------

screenshot_dir=$(xdg-user-dir PICTURES)/Screenshots/

# Check save directory
# Create it if it doesn't exist
function check_dir() {
	if [ ! -d "$screenshot_dir" ];
	then
		mkdir -p "$screenshot_dir"
	fi
}

# Main function
function shot() {

	check_dir

	save_dir="${screenshot_dir}"

	maim_command="maim -u -l -b 0 -c 0,0,0,0.4"

	notif_message="Screenshot saved !"

	if [ "$1" = 'area' ];
	then
		maim_command="$maim_command -s"
	fi

	if [ "$2" = 'copy' ];
	then
		save_dir="/tmp/"
		notif_message="Screenshot copied to clipboard !"
	fi

	file_loc="${save_dir}$(date +%Y%m%d_%H%M%S).png"

	# Execute maim command
	${maim_command} "${file_loc}"

	# Exit if the user cancels the screenshot
	# So it means there's no new screenshot image file
	if [ ! -f "${file_loc}" ];
	then
		exit;
	fi

	# Copy to clipboard
	xclip -selection clipboard -t image/png -i "${save_dir}"/`ls -1 -t "${save_dir}" | head -1` &

	awesome-client "

	-- IMPORTANT NOTE: THIS PART OF THE SCRIPT IS LUA!
	naughty = require('naughty')
	awful = require('awful')
	beautiful = require('beautiful')
	dpi = beautiful.xresources.apply_dpi

	local open_image = naughty.action {
		name = 'Open',
	   	icon_only = false,
	}

	local open_folder = naughty.action {
		name = 'Open Folder',
	   	icon_only = false,
	}

	local delete_image = naughty.action {
		name = 'Delete',
	   	icon_only = false,
	}

	-- Execute the callback when 'Open' is pressed
	open_image:connect_signal('invoked', function()
		awful.spawn('xdg-open ' .. '${file_loc}', false)
	end)

	open_folder:connect_signal('invoked', function()
		awful.spawn('xdg-open ' .. '${save_dir}', false)
	end)

	-- Execute the callback when 'Delete' is pressed
	delete_image:connect_signal('invoked', function()
		awful.spawn('gio trash ' .. '${file_loc}', false)
	end)

	-- Show notification
	naughty.notification ({
		app_name = 'Screenshot Tool',
		icon = '${file_loc}',
		timeout = 10,
		title = '<b>Snap!</b>',
		message = '${notif_message}',
		actions = { open_image, open_folder, delete_image }
	})
	"

}

# Take appropriate action
case $1 in

	full)
		shot full copy
		;;
	selection)
		shot area copy
		;;

	full_saved)
		shot full save
		;;
	selection_saved)
		shot area save
		;;
	*)
		echo "
		Requires an argument:
		full 				- Full screenshot to clipboard
		selection 			- Selection screenshot to clipboard
		full_saved 			- Full screenshot
		selection_saved 	- Selection screenshot
		"
		;;

esac

